
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("502x534")
window.configure(bg = "#292929")


canvas = Canvas(
    window,
    bg = "#292929",
    height = 534,
    width = 502,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    251.0,
    267.0,
    image=image_image_1
)

canvas.create_rectangle(
    115.0,
    163.0,
    384.0,
    336.0,
    fill="#202020",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=274.0,
    y=486.0,
    width=65.0,
    height=19.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=154.0,
    y=486.0,
    width=65.0,
    height=19.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=190.0,
    y=118.0,
    width=141.0,
    height=20.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=287.0,
    y=80.0,
    width=141.0,
    height=20.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=104.0,
    y=80.0,
    width=141.0,
    height=20.0
)

canvas.create_text(
    269.0,
    382.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    290.0,
    382.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    282.0,
    382.0,
    anchor="nw",
    text="/",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    269.0,
    403.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    290.0,
    403.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    282.0,
    403.0,
    anchor="nw",
    text="/",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    269.0,
    425.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    290.0,
    425.0,
    anchor="nw",
    text="0",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    282.0,
    425.0,
    anchor="nw",
    text="/",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
